# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0002_auto_20170326_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performer',
            old_name='facebook_id',
            new_name='performer_id',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='linkedin_id',
            new_name='venueid',
        ),
    ]
