# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 20:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0005_auto_20170322_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('performer_id', models.CharField(max_length=30, unique=True)),
                ('birthday', models.CharField(blank=True, max_length=30, verbose_name='birthday')),
                ('bio', models.CharField(blank=True, max_length=100, verbose_name='bio')),
                ('gender', models.CharField(blank=True, max_length=30, verbose_name='gender')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='status')),
                ('youtube', models.CharField(blank=True, max_length=100, verbose_name='youtube link')),
                ('soundcloud', models.CharField(blank=True, max_length=100, verbose_name='soundcloud link')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='location string')),
            ],
            options={
                'verbose_name': 'Performer',
            },
            bases=('performer.user',),
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='soundcloud',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='youtube',
        ),
    ]
