# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 20:31
from __future__ import unicode_literals

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0005_auto_20170327_2029'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='performer',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='venue',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='performer',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='performer',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='performer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='performer',
            name='soundcloud',
        ),
        migrations.RemoveField(
            model_name='performer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='performer',
            name='youtube',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.AlterField(
            model_name='performer',
            name='performer_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username'),
        ),
    ]
