# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0006_auto_20170326_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performer',
            name='location',
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=30, verbose_name='location string'),
        ),
    ]
