# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0004_auto_20170322_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=100, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='soundcloud',
            field=models.CharField(blank=True, max_length=100, verbose_name='soundcloud link'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='youtube',
            field=models.CharField(blank=True, max_length=100, verbose_name='youtube link'),
        ),
    ]
