# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0007_auto_20170328_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_pv',
            field=models.CharField(blank=True, max_length=1, verbose_name='Type: '),
        ),
    ]
